/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353535",
        "surface-bright": "#393939",
        "surface-tint": "#c6c6c7",
        "outline-variant": "#444748",
        "surface-container-high": "#2a2a2a",
        "on-secondary-container": "#b7b5b4",
        "on-error": "#690005",
        "secondary": "#c8c6c5",
        "tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#464747",
        "on-primary": "#2f3131",
        "surface": "#131313",
        "primary": "#ffffff",
        "background": "#131313",
        "on-surface": "#e2e2e2",
        "surface-container-low": "#1b1b1b",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "inverse-surface": "#e2e2e2",
        "primary-container": "#e2e2e2",
        "inverse-on-surface": "#303030",
        "on-secondary-fixed-variant": "#474746",
        "glass-white": "rgba(255, 255, 255, 0.05)",
        "secondary-container": "#474746",
        "primary-fixed-dim": "#c6c6c7",
        "tertiary-fixed-dim": "#c7c6c6",
        "border-subtle": "#262626",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-primary": "#5d5f5f",
        "secondary-fixed": "#e5e2e1",
        "error": "#ffb4ab",
        "tertiary-container": "#e3e2e2",
        "primary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#636565",
        "on-primary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#454747",
        "surface-high": "#111111",
        "on-surface-variant": "#c4c7c8",
        "tertiary-fixed": "#e3e2e2",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#1b1c1c",
        "on-background": "#e2e2e2",
        "outline": "#8e9192",
        "on-secondary": "#313030",
        "on-tertiary": "#303031",
        "surface-container": "#1f1f1f",
        "surface-variant": "#353535",
        "on-tertiary-container": "#646464"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "gutter": "24px",
        "sm": "12px",
        "margin-mobile": "16px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "xs": "4px",
        "margin-desktop": "64px",
        "container-max": "1440px"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [],
}
